name: valiform
description: 'Valiform is a Flutter form validation library based on Validart. It provides efficient and reactive validations for various field types.'
version: 0.0.1
repository: https://github.com/edunatalec/valiform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  validart: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
